# CSV Operations Notebook  
This notebook contains various commands for performing operations regarding manipulation of data files.

In [1]:
import csv_file_combiner as cfc
from ML_code import util

## List csv files in folder

In [2]:
folder_path = "D:/Vis_network_data/to_be_added_to_main_file/23_04_17-4_30"
csv_files = cfc.get_file_list(folder_path)
for x in csv_files: print(x)


23_04_17_google_batch1_merge.csv
23_04_17_google_batch2_merge.csv
23_04_18_google_batch1_merge.csv
23_04_18_google_batch2_merge.csv
23_04_20_google_batch1_merge.csv
23_04_20_google_batch2_merge.csv
23_04_20_google_batch3_merge.csv
23_04_23_google_batch1_merge.csv
23_04_23_google_batch2_merge.csv
23_04_25_google_batch1_merge.csv
23_04_27_google_batch1_merge.csv
23_04_28_google_batch1_merge.csv
23_04_28_google_batch2_merge.csv
23_04_30_google_batch1_merge.csv
23_04_30_google_batch2_merge.csv


## Count Lines
### In One File

In [3]:
counting_file = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses1.csv"
row_gen = cfc.csv_reader(counting_file)
row_count = cfc.row_counter(row_gen)
print(f'number of rows = {row_count}')

number of rows = 25000


### All Files in Directory

In [4]:
# counting_dir = "D:/Vis_network_data/data_file_by_course"
# total_rows = cfc.count_rows_in_dir(counting_dir)
# print(f'total rows = {total_rows}')

    

In [5]:
# counting_dir = "D:/Vis_network_data/data_file_by_course"
# total_rows = cfc.other_count_rows_in_dir(counting_dir)
# print(f'total rows = {total_rows}')

### Count Number of Zero Lines

In [6]:
# file_path = './results_merge/3_11_main_data_file.csv'
file_path = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses1.csv"
num_zero_lines = cfc.count_zero_lines(file_path)
print(f'num_zero_lines = {num_zero_lines}')

num_zero_lines = 0


## List Directories in a Given Path

## Shift Data

In [7]:
# file_path = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses20.csv"
# f_gen = cfc.csv_reader(file_path)
# row = next(f_gen)
# # print(row)
# values = row.split(',')
# values = [float(x) for x in values]
# print(values)

# num_obs = 20
# num_rows = 3*num_obs
# interval = 2
# result_list = []

# for ii in range(len(values)):
#     if ii > 3 and (ii-4) % (interval + 1) < interval and ii < len(values)-num_obs-1:
#         result_list.append(values[ii] - 15)
#     elif ii < 4:
#         result_list.append(values[ii] - 15)
#     else:
#         result_list.append(values[ii])

# print(result_list)
# if len(values) == len(result_list):
#     print('lists are same length')
# else:
#     print('lists different lengths')



In [8]:
import numpy as np



file_path = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses3.csv"
num_obs = 3
f_gen = cfc.csv_reader(file_path)
string1 = next(f_gen)
string2 = next(f_gen)

array1 = np.array([float(val) for val in string1.split(',')])
array2 = np.array([float(val) for val in string2.split(',')])
result_array = np.vstack((array1, array2))
print(result_array)

modified_array = util.shift_data_set(result_array,num_obs)
print(modified_array)

if result_array.shape == modified_array.shape:
    print('arrays are same length')
else:
    print('arrays different lengths')

[[ 0.          0.         23.11478323  0.         18.00497084  9.06902576
   2.50774597 16.40918315 21.65465788  5.83494798  8.36309182  6.5811889
   1.          0.          0.          0.         23.11478323]
 [ 0.          0.         23.97543533  0.         18.00497084  9.06902576
   2.50774597 16.40918315 21.65465788  5.83494798  8.36309182  6.5811889
   1.          0.          0.          0.         23.97543533]]
[[-15.         -15.           8.11478323 -15.           3.00497084
   -5.93097424   2.50774597   1.40918315   6.65465788   5.83494798
   -6.63690818  -8.4188111    1.           0.           0.
    0.          23.11478323]
 [-15.         -15.           8.97543533 -15.           3.00497084
   -5.93097424   2.50774597   1.40918315   6.65465788   5.83494798
   -6.63690818  -8.4188111    1.           0.           0.
    0.          23.97543533]]
arrays are same length


In [9]:
import numpy as np



file_path = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses3.csv"
num_obs = 3
f_gen = cfc.csv_reader(file_path)
string1 = next(f_gen)
string2 = next(f_gen)

array1 = np.array([float(val) for val in string1.split(',')])
array2 = np.array([float(val) for val in string2.split(',')])
result_array = np.vstack((array1, array2))
print(result_array)

modified_array = np.empty_like(result_array)
for ii, row in enumerate(result_array):
    mod_row = util.shift_row(row,num_obs)
    modified_array[ii,:] = np.array(mod_row)
print(modified_array)

if result_array.shape == modified_array.shape:
    print('arrays are same length')
else:
    print('arrays different lengths')



[[ 0.          0.         23.11478323  0.         18.00497084  9.06902576
   2.50774597 16.40918315 21.65465788  5.83494798  8.36309182  6.5811889
   1.          0.          0.          0.         23.11478323]
 [ 0.          0.         23.97543533  0.         18.00497084  9.06902576
   2.50774597 16.40918315 21.65465788  5.83494798  8.36309182  6.5811889
   1.          0.          0.          0.         23.97543533]]
[[-15.         -15.           8.11478323 -15.           3.00497084
   -5.93097424   2.50774597   1.40918315   6.65465788   5.83494798
   -6.63690818  -8.4188111    1.           0.           0.
    0.          23.11478323]
 [-15.         -15.           8.97543533 -15.           3.00497084
   -5.93097424   2.50774597   1.40918315   6.65465788   5.83494798
   -6.63690818  -8.4188111    1.           0.           0.
    0.          23.97543533]]
arrays are same length


In [10]:
import numpy as np

# Create a sample NumPy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Iterate through the rows using a for loop
for ii,row in enumerate(data):
    print(ii)
    print(row)

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


## Validate File
### Check if File has Correct \# Columns in each row

In [11]:
num_obs = 1 #number of obstacles
file_to_check = "C:/Users/Robert/git/visibility_NN/ML_code/Data/small_main_data_file_courses1.csv"
expected_num_columns = cfc.calculate_num_columns(num_obs)
is_valid,invalid_rows,total_rows = cfc.data_check(file_to_check,expected_num_columns)
print(f'is_valid = {is_valid}')
if not is_valid: print(f'invalid_rows/total_rows = {invalid_rows}/{total_rows}')

is_valid = True


### Remove Invalid Data from File
This script will read a file that has invalid data (the incorrect number of columns in a row), remove those lines, and output it to a file with the suffix "_fixed".  This can only run if the file has been checked and it is found to have invalid rows.

In [12]:
if not is_valid:
    cfc.remove_invalid_data(fpath)
else:
    print('Data is valid, does not need remove operation.')

Data is valid, does not need remove operation.


## Print Window of Data around a Target Row

In [13]:
file_path = './results_merge/3_11_main_data_file.csv'


back_win = 3  # number of points behind target row to display
forward_win = 5  # number of points in front of target window to display
# target_row = 32447305
target_row = 100
cfc.print_data_window(file_path,target_row,back_win,forward_win)

0.0,0.0,24.97322920555525,10.344827586206897,16.273699456505614,23.221369162921548,1.6788393453475583,10.857663113410087,9.820216380723874,2.376913910584751,19.15322380976505,16.628425491349105,2.914591335958061,20.106099034563645,4.530064357581497,4.027591610408261,10.470368188093214,15.52083604480064,1.2068540722466672,11.697677841978136,20.77980247406274,1.0,7.179826442151695,21.712424564215027,1.0,23.11934386291558,22.42837328039059,1.0,23.963229205555248,10.591172089661784,1.0,9.477849729375848,3.560721963624596,0.6817666399056416,9.766762449833408,25.68111545540389,1.570970394528421,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,27.21805648636077

0.0,0.0,25.531759293826887,10.344827586206897,16.273699456505614,23.221369162921548,1.6788393453475583,10.857663113410087,9.820216380723874,2.376913910584751,19.15322380976505,16.628425491349105,2.